import './style.css';
import {decide,parseCSV,portableForecast} from './domain.js';
const $=selector=>document.querySelector(selector);
const plantMeta={pothos:{name:'Golden pothos',caption:'The easygoing one by the window',number:'01'},monstera:{name:'Monstera deliciosa',caption:'The big-leafed corner companion',number:'02'},basil:{name:'Kitchen basil',caption:'A little green for the next meal',number:'03'}};
let artifact,selected='pothos',awayDays=3,stale=false,customRows=null,customPoints=null,source='recorded_tabpfn',worker,gemmaReady=false,busy=false,pendingQuery=false;
function plantSVG(id){
  const leaves=id==='basil'?[[141,133,-20,.7],[195,154,24,.85],[170,105,5,.8],[118,188,-37,.9],[212,195,33,.9],[158,172,-8,.7],[184,197,20,.8]]:id==='monstera'?[[110,165,-40,1.2],[219,174,30,1.15],[145,100,-15,1.1],[185,91,19,1.0],[129,218,-49,.9],[231,220,44,.8]]:[[138,112,-28,.9],[199,140,25,.9],[106,163,-44,1.0],[196,196,36,.95],[146,184,-20,.9],[234,169,45,.8],[117,227,-31,.8],[191,235,32,.8]];
  return `<svg viewBox="0 0 340 340" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="pot" x1="0" x2="1"><stop stop-color="#c1815c"/><stop offset=".5" stop-color="#dfaa7c"/><stop offset="1" stop-color="#c68b60"/></linearGradient><linearGradient id="leaf"><stop stop-color="#4e753e"/><stop offset=".55" stop-color="#6d9653"/><stop offset="1" stop-color="#91b369"/></linearGradient></defs><ellipse cx="172" cy="320" rx="70" ry="10" fill="#bdcba8" opacity=".3"/><g fill="none" stroke="#648b4e" stroke-width="3" stroke-linecap="round"><path d="M171 266 Q153 201 149 124"/><path d="M170 265 Q187 197 204 143"/><path d="M166 260 Q124 222 107 176"/><path d="M177 265 Q206 225 235 179"/><path d="M171 258 Q185 153 177 97"/></g>${leaves.map(([x,y,r,s])=>`<g transform="translate(${x} ${y}) rotate(${r}) scale(${s})"><path d="M0 28C-40 21-41-24-5-39C28-37 41-1 0 28Z" fill="url(#leaf)"/><path d="M0 25Q-3-1-5-32M-2 6L-20-3M-3-9L12-22" fill="none" stroke="#c4d9a1" stroke-width="1" opacity=".6"/></g>`).join('')}<ellipse cx="170" cy="267" rx="52" ry="13" fill="#a16c49"/><path d="M117 266L127 310Q170 328 213 310L223 266Z" fill="url(#pot)"/><ellipse cx="170" cy="266" rx="53" ry="14" fill="#d9a57a"/><ellipse cx="170" cy="266" rx="43" ry="9" fill="#6e5540"/><path d="M170 266V248" stroke="#5c8047" stroke-width="4"/><path d="M128 281Q161 291 210 282" fill="none" stroke="#eac6a5" stroke-width="1" opacity=".5"/></svg>`;
}
function current(){return artifact.scenarios.find(p=>p.id===selected)}
function points(){return customPoints||current().points}
const meanings={WAIT:{title:'Let it be. You’re in the clear.',body:'The forecast stays above the check-soil threshold for your time away. Check the soil when you return.',signal:'No extra attention is forecast yet.',color:'#aec88d',icon:'✓'},CHECK:{title:'A small check, before a big drink.',body:'The soil may be getting dry. Feel the top layer and check the pot before deciding whether to water.',signal:'Check the soil before watering.',color:'#d5b975',icon:'!'},ASK_FRIEND:{title:'A friend can lend a little care.',body:'The forecast may cross the check-soil threshold while you’re away. Ask a friend to check the soil, not to water on a fixed schedule.',signal:'A soil check may be needed while you’re away.',color:'#d4a07b',icon:'♡'},VERIFY_SENSOR:{title:'A fresh reading comes first.',body:'This sensor reading is stale. Check the sensor and the soil in person; a forecast from old data should not decide care.',signal:'Verify the sensor before trusting a forecast.',color:'#b3a2cc',icon:'?'}};
function activeAction(){return decide(current().current,points()[Math.max(awayDays,1)].lower,awayDays,stale)}
function update(){
  const plant=current(),meta=plantMeta[selected],p=points(),cross=p.find(v=>v.lower<22),action=activeAction(),meaning=meanings[action];
  $('#plant-art').innerHTML=plantSVG(selected);$('#plant-name').textContent=meta.name;$('#plant-location').textContent=meta.caption;$('.plant-number').textContent=meta.number;$('.plant-card-top .small').textContent=`${meta.number} / 03`;
  $('#moisture').textContent=Math.round(plant.current);$('#temperature').textContent=plant.temperature;$('#humidity').textContent=plant.humidity;
  $('#forecast-title').textContent=stale?'A fresh reading will help.':cross?`Plan a soil check ${cross.day===1?'tomorrow':`in about ${cross.day} days`}.`:'A comfortable week ahead.';
  $('#forecast-subtitle').textContent=source==='recorded_tabpfn'?'Recorded TabPFN forecast · simulated plant history':source==='live_local_tabpfn'?'Live local TabPFN inference · your CSV':'Portable analogue baseline · your CSV · not TabPFN';
  $('.model-label').textContent=source==='portable_baseline'?'Portable baseline':'TabPFN v2';
  $('#days-output').textContent=awayDays===0?'At home':`${awayDays} ${awayDays===1?'day':'days'}`;
  $('#plan-title').textContent=meaning.title;$('#plan-body').textContent=meaning.body;$('#plan-icon').textContent=meaning.icon;
  $('#device-signal').textContent=action.replaceAll('_',' ');$('#device-description').textContent=meaning.signal;$('#led-ring').style.borderColor=meaning.color;$('#led-ring').style.boxShadow=`0 0 13px ${meaning.color}77,inset 0 0 8px ${meaning.color}55`;
  document.querySelectorAll('.plant-tab').forEach(b=>{b.classList.toggle('selected',b.dataset.plant===selected);b.setAttribute('aria-pressed',String(b.dataset.plant===selected))});
  renderChart(p);
}
function renderChart(p){
  const x=d=>48+d*74,y=v=>190-v*1.75;
  const line=p.map(v=>`${x(v.day)},${y(v.mean)}`).join(' ');
  const band=p.map(v=>`${x(v.day)},${y(v.upper)}`).concat([...p].reverse().map(v=>`${x(v.day)},${y(v.lower)}`)).join(' ');
  $('#forecast-chart').innerHTML=`<title>Seven-day soil moisture forecast</title><desc>Predicted moisture falls from ${p[0].mean.toFixed(0)} percent today to ${p[7].mean.toFixed(0)} percent in seven days. The shaded region is an estimated range.</desc>${[20,40,60,80].map(v=>`<line x1="48" x2="566" y1="${y(v)}" y2="${y(v)}" stroke="#edf1e8"/><text x="28" y="${y(v)+4}" text-anchor="end" fill="#a1aa96" font-size="11">${v}%</text>`).join('')}<line x1="48" x2="566" y1="${y(22)}" y2="${y(22)}" stroke="#c7a480" stroke-dasharray="5 5"/><polygon points="${band}" fill="#d7e7bf" opacity=".65"/><polyline points="${line}" fill="none" stroke="#668650" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/>${p.map(v=>`<circle cx="${x(v.day)}" cy="${y(v.mean)}" r="${v.day===awayDays?5:3}" fill="${v.day===awayDays?'#244a35':'#fff'}" stroke="#668650" stroke-width="1.5"><title>Day ${v.day}: ${v.mean.toFixed(1)}%, estimated range ${v.lower.toFixed(1)}–${v.upper.toFixed(1)}%</title></circle><text x="${x(v.day)}" y="217" text-anchor="middle" fill="#9aa590" font-size="11">${v.day===0?'Today':`Day ${v.day}`}</text>`).join('')}`;
}
function careNote(){const p=current();return `Stillroot care note for ${plantMeta[selected].name}\nAway: ${awayDays} days\nCurrent relative moisture: ${p.current}%\nCare signal: ${activeAction()}\n${meanings[activeAction()].body}\nDo not water automatically. Check soil and drainage first.\nData: ${source==='recorded_tabpfn'?'synthetic demo, recorded TabPFN forecast':source}.`}
function download(text,name,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
document.querySelectorAll('.plant-tab').forEach(b=>b.addEventListener('click',()=>{selected=b.dataset.plant;customPoints=null;source='recorded_tabpfn';update()}));
$('#away-days').addEventListener('input',e=>{awayDays=Number(e.target.value);update()});
$('#stale-sensor').addEventListener('change',e=>{stale=e.target.checked;update()});
$('#reset').addEventListener('click',()=>{selected='pothos';awayDays=3;stale=false;customRows=null;customPoints=null;source='recorded_tabpfn';$('#away-days').value=3;$('#stale-sensor').checked=false;$('#csv-upload').value='';$('#csv-status').textContent='No file selected';$('#local-forecast').disabled=true;$('#copy-status').textContent='';update()});
$('#copy-plan').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(careNote());$('#copy-status').textContent='Copied'}catch{$('#copy-status').textContent='Clipboard unavailable. Use Save plan.'}});
$('#download-plan').addEventListener('click',()=>download(careNote(),'stillroot-care-note.txt'));
$('#csv-upload').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>200000)throw new Error('Please use a file smaller than 200 KB.');customRows=parseCSV(await file.text());customPoints=portableForecast(customRows,current().current,current());source='portable_baseline';$('#csv-status').textContent=`${customRows.length} rows · portable baseline · stays in this browser`;$('#local-forecast').disabled=false;update()}catch(error){$('#csv-status').textContent=error.message;$('#csv-status').classList.add('failure');customRows=null;$('#local-forecast').disabled=true}});
$('#local-forecast').addEventListener('click',async()=>{if(!customRows)return;$('#local-forecast').disabled=true;$('#csv-status').textContent='Running local TabPFN…';try{const p=current();const response=await fetch('http://127.0.0.1:8000/api/forecast',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rows:customRows,current:p.current,temperature:p.temperature,humidity:p.humidity,light_hours:p.light_hours,pot_size:p.pot_size})});const result=await response.json();if(!response.ok)throw new Error(result.detail||'Local forecast unavailable');customPoints=result.points;source=result.source;$('#csv-status').textContent='Live TabPFN result · processed on your local runtime';update()}catch(e){$('#csv-status').textContent=`Local runtime unavailable. Start it using the README; the browser baseline still works.`}finally{$('#local-forecast').disabled=false}});
function setChat(text){$('#chat-output').replaceChildren();const icon=document.createElement('span');icon.className='chat-mark';icon.textContent='✳';const content=document.createElement('div');content.style.whiteSpace='pre-wrap';content.textContent=text;$('#chat-output').append(icon,content)}
function ensureWorker(){if(worker)return;worker=new Worker(new URL('./gemma-worker.js',import.meta.url),{type:'module'});worker.onmessage=({data})=>{if(data.type==='status'){$('#model-status').textContent=data.text}if(data.type==='progress' && data.status==='progress'){$('#model-status').textContent=`Loading Gemma · ${data.file?.split('/').at(-1)} · ${Math.round(data.progress||0)}%`}if(data.type==='ready'){gemmaReady=true;$('#ask-button').textContent='Ask Gemma';$('#model-status').textContent='Gemma is ready. Questions are processed locally in this browser.';if(!pendingQuery){busy=false;$('#ask-button').disabled=false}}if(data.type==='token')setChat(data.text);if(data.type==='done'){setChat(data.text);busy=false;pendingQuery=false;$('#ask-button').disabled=false;$('#ask-button').textContent='Ask Gemma';$('#model-status').textContent=`Answered locally by Gemma 3 270M in ${(data.duration_ms/1000).toFixed(1)}s. Check the soil before acting on advice.`}if(data.type==='error'){setChat(`Gemma couldn’t run on this device: ${data.text}\nYour forecast and care plan still work. Try a recent Chrome or Edge browser.`);$('#model-status').textContent='The model did not answer. No response has been substituted.';busy=false;pendingQuery=false;$('#ask-button').disabled=false;$('#ask-button').textContent='Try Gemma again';worker.terminate();worker=null;gemmaReady=false}};worker.onerror=e=>{setChat('Gemma encountered a browser error. The forecast still works. Try reloading.');busy=false;$('#ask-button').disabled=false}}
async function ask(question){if(busy||!artifact)return;ensureWorker();busy=true;pendingQuery=Boolean(question);$('#ask-button').disabled=true;$('#ask-button').textContent=gemmaReady?'Thinking…':'Loading…';if(!question){worker.postMessage({type:'load'});return}const p=current(),point=points()[Math.max(awayDays,1)];setChat(gemmaReady?'Thinking on your device…':'Preparing your private plant companion…');worker.postMessage({type:'generate',prompt:`You help a friend care for a houseplant. Answer briefly in plain English. Do not claim to see a real plant. Never give a watering volume or diagnose disease. Tell the person to check soil and drainage before watering.\nFacts: Plant: ${plantMeta[selected].name}. Relative moisture ${p.current}%. ${awayDays} days away. Forecast lower estimate ${point.lower.toFixed(1)}%. Reading ${stale?'STALE: verify sensor before advice':'is a simulated demo reading'}. Care signal ${activeAction()}.\nQuestion: ${question}\nAnswer in two sentences:`})}
$('#chat-form').addEventListener('submit',e=>{e.preventDefault();ask($('#question').value.trim())});
document.querySelectorAll('[data-question]').forEach(b=>b.addEventListener('click',()=>{$('#question').value=b.dataset.question;ask(b.dataset.question)}));
async function init(){try{const response=await fetch('/data/forecasts.json');if(!response.ok)throw new Error('The forecast artifact is unavailable.');artifact=await response.json();update();const report=await fetch('/data/tabpfn-report.json').then(r=>r.json());$('#tabpfn-score').innerHTML=`${report.tabpfn_mae.toFixed(2)} <small>points</small>`;$('#baseline-score').innerHTML=`${report.baselines.mean_training_drop.toFixed(2)} <small>points</small>`;$('#coverage-score').innerHTML=`${(report.test_interval_coverage*100).toFixed(0)}<small>%</small>`;}catch(e){$('#forecast-title').textContent='Forecast unavailable';$('#forecast-subtitle').textContent=e.message;$('#plan-title').textContent='A forecast is needed first.';$('#plan-body').textContent='Check the soil in person. Please reload to retry.'}}
function registerCareTools(){
  const context=document.modelContext;
  if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  const readPlan=()=>{
    if(!artifact)throw new Error('Forecast is still loading.');
    return {plant:selected,days_away:awayDays,stale,signal:activeAction(),data_source:source,note:careNote()};
  };
  const definitions=[
    {name:'read_care_plan',title:'Read care plan',description:'Read the visible plant, trip duration, care signal, and downloadable note. No messages are sent.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected an empty object.');return readPlan();}},
    {name:'configure_demo_care_plan',title:'Configure demo care plan',description:'Choose a simulated plant, days away, and stale-reading state. Update the same visible forecast and care note as the controls. No messages are sent.',inputSchema:{type:'object',properties:{plant:{type:'string',enum:Object.keys(plantMeta)},days_away:{type:'integer',minimum:0,maximum:7},stale:{type:'boolean'}},required:['plant','days_away','stale'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){
      if(!artifact)throw new Error('Forecast is still loading.');
      if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).some(k=>!['plant','days_away','stale'].includes(k))||!Object.hasOwn(plantMeta,input.plant)||!Number.isInteger(input.days_away)||input.days_away<0||input.days_away>7||typeof input.stale!=='boolean')throw new Error('Choose a valid demo plant, 0–7 days away, and a boolean stale flag.');
      selected=input.plant;awayDays=input.days_away;stale=input.stale;customPoints=null;source='recorded_tabpfn';
      $('#away-days').value=awayDays;$('#stale-sensor').checked=stale;update();return readPlan();
    }}
  ];
  for(const definition of definitions){try{Promise.resolve(context.registerTool(definition,{signal:lifecycle.signal})).catch(()=>{});}catch{}}
  window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
init().then(registerCareTools);
